name: Build mycelo image

on:
  push:
    branches:
      - master
      - jcortejoso/mycelo-image

  pull_request:
    branches:
      - master

concurrency: 
  group: mycelo-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-system-contracts:
    name: Build celo-monorepo
    runs-on: [self-hosted, blockchain, 8-cpu]
    steps:
      - name: Checkout celo-blockchain repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build mycelo image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.mycelo
          push: false
          tags: mycelo:latest
      - name: Check docker images
        run: docker images
